services:
  mysql:
    image: mysql:9.4
    container_name: library_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d