USE library_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS book_author;
DROP TABLE IF EXISTS loan;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS author;


SET FOREIGN_KEY_CHECKS = 1;